name: Self Test
on: [push]
jobs:
  self-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Tests the action using itself
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Provision
      run: npm update
    
    - name: Install
      uses: ./
      id: install
      with:
        command: 'install'
    
    - name: Generate Hello World
      run: echo 'println("hello, github!")' > test.stanza
    
    - name: Run Hello World
      uses: ./
      id: run-hello
      with:
        command: run test.stanza
  
    - name: Generate Test 
      run: |
        echo '#use-added-syntax(tests)' > test.stanza
        echo 'deftest my-test:'        >> test.stanza
        echo '  println("Test Executed Successfully")' >> test.stanza

    - name: Compile Tests
      uses: ./
      id: compile-test
      with:
        command: compile-test test.stanza -o run-test
      
    - name: Run Tests
      id: run-tests
      run: ./run-test
